### ISSUE TITLE
No readme, no LICENSE

### ISSUE THREAD

**Issue by langford** [drewag/swift-serve#1]
Your code your rules. 

What this is and what it does and how to easily make it do it aren't obvious by looking at this.

**Comment by drewag** [comment]
I agree. The reality is that this framework is not ready for public consumption. It needs a lot more than a Readme and a License. It needs true documentation. I use it in several projects but I have not had the time to make the necessary changes for it to be accessible to other developers.

Since you seem curious, it is a framework for developing server side swift websites and services. My goal in developing it was to provide myself an abstraction that I can write all of my websites and web services against that allows me to switch between other frameworks easily (e.g. Zewo and Kitura) without rewriting the application level code. The advantage for me is that I wrote it exactly the way I want things to work. I am not sure I see the attraction for other developers as they can just use Zewo, Kitura, or whatever directly. As it matures and if I see a reason it would be attractive to other developers, I will certainly try to make it more accessible.

**Comment by langford** [comment]
It was called out as a swift platform on the iOS developer slack was why I
was asking.

Thank you for the explanation!




--
Michael Langford
http://www.RowdyLabs.com
